version: "3"

services:
  minio:
    image: minio/minio
    # image: minio/minio:RELEASE.2020-09-17T04-49-20Z-arm64
    command: server /data
    container_name: minio
    network_mode: bridge
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=${ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${SECRET_KEY}"
    volumes:
      - ${S4_ROOT}/minio:/data

  ipfs:
    image: ideea/s4-ipfs
    # image: ideea/s4-ipfs:arm64v8
    container_name: ipfs
    network_mode: bridge
    restart: always
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - ${S4_ROOT}/minio:/s4
      - ${S4_ROOT}/ipfs:/ipfs
    environment:
      - "IPFS_PATH=/ipfs"

  tor-proxy:
    image: ideea/s4-tor-proxy
    # image: ideea/s4-tor-proxy:arm64v8
    container_name: tor-proxy
    network_mode: bridge
    restart: always
    volumes:
      - ${S4_ROOT}/tor:/web
    depends_on:
      - minio
    links:
      - minio
